[CONFIG]
CLIST=ON
FLIST=ON
WAIT=ON
FMODE=OFF

[TARGET]
URL=https://www.example.com/PFZG
LIST=HOLA,XS,TU
WORDLIST=wordlist.txt
SLEEP=1

# Visit https://github.com/infernoidpl4y/P0w3rFuzz1ng